#!/bin/bash

# Build script for PicoBOB G540
# This script configures and builds grblHAL for the PicoBOB G540 board

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Building grblHAL for PicoBOB G540${NC}"
echo "=================================="

# Check if we're in the right directory
if [ ! -f "CMakeLists.txt" ]; then
    echo -e "${RED}Error: CMakeLists.txt not found. Please run this script from the RP2040 directory.${NC}"
    exit 1
fi

# Check for required tools and install if needed
echo -e "${YELLOW}Checking for required tools...${NC}"
MISSING_TOOLS=""
if ! command -v cmake &> /dev/null; then
    MISSING_TOOLS="cmake"
fi
if ! command -v arm-none-eabi-gcc &> /dev/null; then
    MISSING_TOOLS="$MISSING_TOOLS gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib"
fi

if [ -n "$MISSING_TOOLS" ]; then
    echo -e "${YELLOW}Installing missing tools: $MISSING_TOOLS${NC}"
    sudo apt-get update
    sudo apt-get install -y $MISSING_TOOLS
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to install required tools!${NC}"
        exit 1
    fi
fi

# Initialize and update git submodules if needed
echo -e "${YELLOW}Checking git submodules...${NC}"
if [ -d ".git" ]; then
    # Check if submodules are initialized
    if [ ! -f "grbl/CMakeLists.txt" ]; then
        echo -e "${YELLOW}Initializing git submodules...${NC}"
        git submodule update --init --recursive
        if [ $? -ne 0 ]; then
            echo -e "${RED}Failed to initialize git submodules!${NC}"
            exit 1
        fi
    fi
fi

# Check if driverPIO.pio.h exists, if not we'll need to handle it
if [ ! -f "driverPIO.pio.h" ]; then
    echo -e "${YELLOW}driverPIO.pio.h not found. Attempting to generate it...${NC}"
    
    # Try to build pioasm if not available or has GLIBC issues
    if ! command -v pioasm &> /dev/null || ! pioasm --version &> /dev/null 2>&1; then
        echo -e "${YELLOW}Building pioasm from source...${NC}"
        if [ -d "$PICO_SDK_PATH" ]; then
            PIOASM_BUILD_DIR="/tmp/pioasm_build"
            rm -rf "$PIOASM_BUILD_DIR"
            mkdir -p "$PIOASM_BUILD_DIR"
            cd "$PIOASM_BUILD_DIR"
            cmake "$PICO_SDK_PATH/tools/pioasm" 2>/dev/null
            make -j$(nproc) 2>/dev/null
            if [ -f "pioasm" ]; then
                export PATH="$PIOASM_BUILD_DIR:$PATH"
                echo -e "${GREEN}pioasm built successfully${NC}"
                cd - > /dev/null
                # Try to generate the header file
                pioasm -o c-sdk driverPIO.pio driverPIO.pio.h 2>/dev/null
            else
                cd - > /dev/null
                echo -e "${YELLOW}pioasm build failed. The build may fail if driverPIO.pio.h is not pre-generated.${NC}"
                echo -e "${YELLOW}You may need to generate driverPIO.pio.h on a system with proper GLIBC version.${NC}"
            fi
        fi
    else
        # pioasm is available, try to use it
        pioasm -o c-sdk driverPIO.pio driverPIO.pio.h 2>/dev/null
    fi
fi

# Create a temporary my_machine.h with PicoBOB G540 configuration
echo -e "${YELLOW}Creating PicoBOB G540 configuration...${NC}"
cp my_machine.h my_machine.h.backup 2>/dev/null

cat > my_machine.h << 'EOF'
/*
  my_machine.h - configuration for PicoBOB G540 build
  
  Auto-generated by build_picobob_g540.sh
*/

// Enable PicoBOB G540 board
#define BOARD_PICOBOB_G540

// Configuration
#define USB_SERIAL_CDC          1 // Serial communication via native USB

// Optional features (uncomment to enable)
//#define SDCARD_ENABLE           2 // Run gcode programs from SD card. Set to 2 to enable YModem upload
//#define PROBE_ENABLE            1 // Enable probe input
//#define COOLANT_ENABLE          3 // Enable coolant control (flood)

// Control signals
#define CONTROL_ENABLE          (CONTROL_HALT|CONTROL_FEED_HOLD) // Enable halt and feed hold

// Spindle configuration
#define DRIVER_SPINDLE_ENABLE   (SPINDLE_PWM|SPINDLE_ENA) // PWM spindle with enable

// Default axis configuration is 3 axes (X, Y, Z)
// Uncomment to enable 4th axis (A)
//#define N_ABC_MOTORS 1

/**/
EOF

# Clean previous build if exists
if [ -d "build" ]; then
    echo -e "${YELLOW}Cleaning previous build...${NC}"
    rm -rf build
fi

# Create build directory
mkdir -p build
cd build

# Configure with CMake
echo -e "${YELLOW}Configuring with CMake...${NC}"
cmake -DPICO_BOARD=pico ..

if [ $? -ne 0 ]; then
    echo -e "${RED}CMake configuration failed!${NC}"
    cd ..
    # Restore original my_machine.h
    if [ -f "my_machine.h.backup" ]; then
        mv my_machine.h.backup my_machine.h
    fi
    exit 1
fi

# Build the project
echo -e "${YELLOW}Building project...${NC}"
make -j$(nproc)

if [ $? -ne 0 ]; then
    echo -e "${RED}Build failed!${NC}"
    cd ..
    # Restore original my_machine.h
    if [ -f "my_machine.h.backup" ]; then
        mv my_machine.h.backup my_machine.h
    fi
    exit 1
fi

# Check if build was successful
if [ -f "grblHAL.uf2" ]; then
    echo -e "${GREEN}Build successful!${NC}"
    echo -e "${GREEN}Firmware file: build/grblHAL.uf2${NC}"
    echo ""
    echo "To flash the firmware:"
    echo "1. Hold the BOOTSEL button on your Pico"
    echo "2. Connect the Pico to your computer via USB"
    echo "3. Release the BOOTSEL button"
    echo "4. Copy build/grblHAL.uf2 to the RPI-RP2 drive that appears"
else
    echo -e "${RED}Build completed but grblHAL.uf2 not found!${NC}"
fi

cd ..

# Restore original my_machine.h
if [ -f "my_machine.h.backup" ]; then
    mv my_machine.h.backup my_machine.h
fi

echo -e "${GREEN}Done!${NC}"