#!/bin/bash

# Docker-based build script for PicoBOB G540
# This script uses Docker to build grblHAL in an Ubuntu 22.04 environment

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Docker-based build for grblHAL PicoBOB G540${NC}"
echo "============================================"

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed. Please install Docker first.${NC}"
    exit 1
fi

# Check if we're in the right directory
if [ ! -f "CMakeLists.txt" ]; then
    echo -e "${RED}Error: CMakeLists.txt not found. Please run this script from the RP2040 directory.${NC}"
    exit 1
fi

# Initialize and update git submodules if needed
echo -e "${YELLOW}Checking git submodules...${NC}"
if [ -d ".git" ]; then
    if [ ! -f "grbl/CMakeLists.txt" ]; then
        echo -e "${YELLOW}Initializing git submodules...${NC}"
        git submodule update --init --recursive
        if [ $? -ne 0 ]; then
            echo -e "${RED}Failed to initialize git submodules!${NC}"
            exit 1
        fi
    fi
fi

# Build Docker image
echo -e "${YELLOW}Building Docker image...${NC}"
docker build -f Dockerfile.picobob -t grblhal-picobob-builder .
if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to build Docker image!${NC}"
    exit 1
fi

# Create the my_machine.h configuration
echo -e "${YELLOW}Creating PicoBOB G540 configuration...${NC}"
cat > my_machine.h << 'EOF'
/*
  my_machine.h - configuration for PicoBOB G540 build
  
  Auto-generated by docker_build_picobob_g540.sh
*/

// Enable PicoBOB G540 board
#define BOARD_PICOBOB_G540

// Configuration
#define USB_SERIAL_CDC          1 // Serial communication via native USB

// Optional features (uncomment to enable)
//#define SDCARD_ENABLE           2 // Run gcode programs from SD card. Set to 2 to enable YModem upload
//#define PROBE_ENABLE            1 // Enable probe input
//#define COOLANT_ENABLE          3 // Enable coolant control (flood)

// Control signals
#define CONTROL_ENABLE          (CONTROL_HALT|CONTROL_FEED_HOLD) // Enable halt and feed hold

// Spindle configuration
#define DRIVER_SPINDLE_ENABLE   (SPINDLE_PWM|SPINDLE_ENA) // PWM spindle with enable

// Default axis configuration is 3 axes (X, Y, Z)
// Uncomment to enable 4th axis (A)
//#define N_ABC_MOTORS 1

/**/
EOF

# Run the build in Docker
echo -e "${YELLOW}Running build in Docker container...${NC}"
docker run --rm -v "$(pwd):/workspace" grblhal-picobob-builder bash -c "
    cd /workspace
    # Clean previous build
    rm -rf build
    mkdir -p build
    cd build
    
    # Configure with CMake
    echo 'Configuring with CMake...'
    cmake -DPICO_BOARD=pico ..
    
    # Build the project
    echo 'Building project...'
    make -j\$(nproc)
    
    # Check if build was successful
    if [ -f 'grblHAL.uf2' ]; then
        echo 'Build successful!'
        ls -la grblHAL.*
    else
        echo 'Build failed - grblHAL.uf2 not found!'
        exit 1
    fi
"

BUILD_RESULT=$?

if [ $BUILD_RESULT -eq 0 ]; then
    echo -e "${GREEN}Build successful!${NC}"
    echo -e "${GREEN}Firmware file: build/grblHAL.uf2${NC}"
    echo ""
    echo "To flash the firmware:"
    echo "1. Hold the BOOTSEL button on your Pico"
    echo "2. Connect the Pico to your computer via USB"
    echo "3. Release the BOOTSEL button"
    echo "4. Copy build/grblHAL.uf2 to the RPI-RP2 drive that appears"
else
    echo -e "${RED}Build failed!${NC}"
fi

echo -e "${GREEN}Done!${NC}"